name: ReactiveX

baseurl: "/reactivex-docs"
destination: "_site/reactivex-docs"

url: "https://qubitpi.github.io"

markdown: kramdown
redcarpet:
   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments
exclude: [TODO, Rakefile, bootstrap, styles]
